runtime: nodejs20
instance_class: F4
env: flex
automatic_scaling:
    min_instances: 1
    max_instances: 2 # Keeps costs low for testing
env_variables:
    NODE_ENV: 'production'
    # Add your DB connection strings here, NOT in .env files
    JWT_SECRET_KEY: 'kfmf5323fvr5d_mlm5105ds'
    MYSQL_USER: 'nanyang60'
    MYSQL_PASSWORD: 'NTUSingapore+60'
    MYSQL_DATABASE: 'nanyang_stars'
    CLOUD_SQL_CONNECTION_NAME: 'mock-ntu-wes:asia-southeast1:nanyang-registrar'
    API_PORT: 8080